import { useState } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { Plus, Minus } from 'lucide-react';

const faqs = [
  {
question: 'How does BlogGalaxy aI generate articles?',
    answer: 'BlogGalaxy AI uses advanced GPT-4 technology combined with our proprietary SEO algorithms. You simply enter a topic, and our AI researches, outlines, and writes a complete article optimized for search engines in minutes.',
  },
  {
    question: 'Is the content original and plagiarism-free?',
    answer: 'Yes! Every article generated by BlogGalaxy ai is 100% original. Our built-in plagiarism checker scans millions of web pages to ensure your content is unique. We also provide a detailed originality report with each article.',
  },
  {
    question: 'Can I edit the AI-generated content?',
    answer: 'Absolutely! BlogGalaxy ai provides a powerful editor where you can refine, customize, and perfect your articles. think of it as your ai co-writer - it does the heavy lifting, and you add your personal touch.',
  },
  {
    question: 'What languages does BlogGalaxy AI support?',
    answer: 'Currently, BlogGalaxy ai supports over 25 languages including English, Spanish, French, German, Portuguese, Italian, Dutch, and more. We\'re constantly adding new languages based on user demand.',
  },
  {
    question: 'How does the team collaboration feature work?',
    answer: 'On Pro and Business plans, you can invite team members, assign different roles (writer, editor, admin), create workflows, and collaborate in real-time. Each member can track their contributions and manage content together.',
  },
  {
    question: 'Can I cancel my subscription anytime?',
    answer: 'Yes, you can cancel your subscription at any time with no questions asked. If you\'re on an annual plan, you can cancel before your renewal date. We also offer a 30-day money-back guarantee if you\'re not satisfied.',
  },
  {
    question: 'Do you offer a free trial?',
    answer: 'Yes! We offer a 14-day free trial on all paid plans. No credit card required to start. You get full access to all features during the trial period.',
  },
  {
    question: 'How does the API access work?',
    answer: 'Business plan subscribers get full API access to integrate BlogGalaxy AI into their own applications and workflows. This includes comprehensive documentation, webhooks, and developer support.',
  },
];

export function FAQ() {
  const [openIndex, setOpenIndex] = useState(null);

  const toggleFAQ = (index) => {
    setOpenIndex(openIndex === index ? null : index);
  };

  return (
    <section id="faq" className="py-20 px-4 sm:px-6 lg:px-8 bg-gray-50 dark:bg-gray-900">
      <div className="max-w-4xl mx-auto">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6 }}
          className="text-center mb-12"
        >
          <h2 className="text-4xl sm:text-5xl font-bold text-gray-900 dark:text-white mb-4">
            Frequently Asked Questions
          </h2>
          <p className="text-xl text-gray-600 dark:text-gray-300">
            Everything you need to know about BlogGalaxy AI.
          </p>
        </motion.div>

        <div className="space-y-4">
          {faqs.map((faq, index) => (
            <motion.div
              key={index}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.6, delay: index * 0.05 }}
              className="bg-white dark:bg-gray-800 rounded-xl border border-gray-200 dark:border-gray-700  overflow-hidden"
            >
              <button
                onClick={() => toggleFAQ(index)}
                className="w-full px-6 py-5 flex items-center justify-between text-left  transition-colors"
                aria-expanded={openIndex === index}
              >
                <span className="font-semibold text-gray-900  dark:text-white pr-8 ">
                  {faq.question}
                </span>
                <div className="flex-shrink-0 w-6 h-6 flex items-center justify-center">
                  {openIndex === index ? (
                    <Minus className="w-5 h-5 text-blue-500" />
                  ) : (
                    <Plus className="w-5 h-5 text-gray-400" />
                  )}
                </div>
              </button>
              
              <AnimatePresence>
                {openIndex === index && (
                  <motion.div
                    initial={{ height: 0, opacity: 0 }}
                    animate={{ height: 'auto', opacity: 1 }}
                    exit={{ height: 0, opacity: 0 }}
                    transition={{ duration: 0.3 }}
                    className="overflow-hidden"
                  >
                    <div className="px-6 pb-5 text-gray-600 dark:text-gray-300 leading-relaxed">
                      {faq.answer}
                    </div>
                  </motion.div>
                )}
              </AnimatePresence>
            </motion.div>
          ))}
        </div>

        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6, delay: 0.4 }}
          className="mt-12 text-center"
        >
          <p className="text-gray-600 dark:text-gray-400 mb-4">
            Still have questions?
          </p>
          <button className="text-blue-500 hover:text-blue-600 font-semibold">
            Contact our support team →
          </button>
        </motion.div>
      </div>
    </section>
  );
}
